### ISSUE TITLE
There is an ability to attach file to message on UI but it's not working

### ISSUE THREAD

**Issue by islamumarov** [MangoInstantMessenger/MangoMessengerAPI#349]
There is an ability to attach file to message on UI but it's not working, when you attach a file try to send it, system asks to add a text message. When you add a text message and file, then send them message sends successfully but file disappears.

1. Add Ability to send just a files and display them on UI (Best practice: send file to object storage form FE and attach link to the message's field _fileLink_
2. add ability to send files with messages and display them

**Comment by kolosovpetro** [comment]
Thanks for the issue, currently I am in progress how to design file attachment process as simple as possible. It is planned feature.

However, If you have vision how to implement it in reliable way -- you are free to contribute :)

**Comment by islamumarov** [comment]
Yep, now I'm working on secure implementation of that and also have some suggestion about separate hardcoded strings inside of html elements to make them reusable.
I also admit that BE architecture is  a lot better than FE

**Comment by kolosovpetro** [comment]
Closed via https://github.com/MangoInstantMessenger/MangoMessengerAPI/pull/354
