### ISSUE TITLE
Refactor dependency injection classes

### ISSUE THREAD

**Issue by kolosovpetro** [MangoInstantMessenger/MangoMessengerAPI#382]
- Remove unused class `MailgunDependencyInjection.cs`
- Remove `MessengerServices.cs` and place all its contents directly to `Startup.cs`
- Remove `MediatorValidatorsAndResponseFactoryDependencyInjection.cs` and place all its contents directly to `Startup.cs`
- Remove `PasswordHashServiceDependencyInjection.cs` and place all its contents directly to `Startup.cs`
- Remove `InfrastructureServices.cs` and place all its contents directly to `Startup.cs`
- Use `SwaggerServices.cs` class inside `Startup.cs` class. Pass there required parameters like version, title etc
- Delete unused `RegisterResponse` class
- Remove `Obsolet` attribute from `CorsServices.cs`
- Delete unused `CngPublicKey.cs`
- Make `MangoModule.RequestAsync()` method static

**Comment by Ketteiteki** [comment]
btw why did you decide to move all registrations services to Startup?

**Comment by Ketteiteki** [comment]
i think it looks dirtier than it was

**Comment by kolosovpetro** [comment]
> btw why did you decide to move all registrations services to Startup?

I want to see all my dependencies in one place, not to run over solution
